modLoader="javafml"
loaderVersion="[1,)"
license="MIT https://github.com/bl4ckscor3/HorizontalReinforcedDeepslate/blob/1.20.4/LICENSE"
issueTrackerURL="http://github.com/bl4ckscor3/HorizontalReinforcedDeepslate/issues"

[[mods]]
	modId="horizontalreinforceddeepslate"
	version="${file.jarVersion}"
	displayName="Horizontal Reinforced Deepslate"
	description='''Allows vanilla's reinforced deepslate to be placed horizontally.'''
	displayURL="https://curseforge.com/minecraft/mc-mods/horizontal-reinforced-deepslate"
	authors="bl4ckscor3"

[[dependencies.horizontalreinforceddeepslate]]
    modId="neoforge"
    mandatory=true
    versionRange="[20.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.horizontalreinforceddeepslate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.3,1.21)"
    ordering="NONE"
    side="BOTH"