modLoader="javafml"
loaderVersion="[1,)"
license="MIT https://github.com/bl4ckscor3/HorizontalReinforcedDeepslate/blob/1.21.11/LICENSE"
issueTrackerURL="http://github.com/bl4ckscor3/HorizontalReinforcedDeepslate/issues"

[[mods]]
	modId="horizontalreinforceddeepslate"
	version="${file.jarVersion}"
	displayName="Horizontal Reinforced Deepslate"
	description='''Allows vanilla's reinforced deepslate to be placed horizontally.'''
	displayURL="https://curseforge.com/minecraft/mc-mods/horizontal-reinforced-deepslate"
	authors="bl4ckscor3"

[[dependencies.horizontalreinforceddeepslate]]
    modId="neoforge"
    type="required"
    versionRange="[21.11,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.horizontalreinforceddeepslate]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.11,)"
    ordering="NONE"
    side="BOTH"